### ISSUE TITLE
anchorPos makes no difference to dragmarker position

### ISSUE THREAD

**Issue by benneca** [ibrierley/flutter_map_dragmarker#1]
I can change the marker anchorPos and the marker is always anchored in the center. I can see that the offset is handled in the dragmarker.dart, but it makes no difference. Any idea of how to get the anchorPos to be utilized? I am trying to add a rotation element to the draggable marker and I need the origin to be at the bottom center.

**Comment by ibrierley** [comment]
Can you just post how you are using it...and are you using feedbackoffset (i.e is there any offset when dragging, or is it when static or both) ?

**Comment by jstnwang0** [comment]
I've noticed this too. If you place a draggable marker and zoom out, the center always remains on the same spot on the map, no matter what anchorPos is.

**Comment by ibrierley** [comment]
Do you want to try it now (I assume you're using dragmarket.dart and not the dragmarker_widget as that was designed more for some old code, but I can change that as well if necessary).
