### ISSUE TITLE
Dependency conflict with flutter_map_tappable_polyline

### ISSUE THREAD

**Issue by JanikoNaber** [ibrierley/flutter_map_dragmarker#10]
Due to the use of latlong2: ^0.8.0. this plugin is incompatible with flutter_map_tappable_polyline: any.

Because every version of flutter_map_dragmarker from git depends on latlong2 0.8.0 and flutter_map_tappable_polyline >=3.1.0 depends on latlong2 ^0.8.1, flutter_map_dragmarker from git is incompatible with flutter_map_tappable_polyline >=3.1.0.

Would it be possible to change the dependency to latlong2 0.8.1?

**Comment by ibrierley** [comment]
Only problem is there's some other packages that rely on it being 0.8.0 still, but I will have a ponder.

**Comment by pablojimpas** [comment]
This issue was fixed, and both packages are compatible now. Thanks for the report @JanikoNaber. Closing…
