### ISSUE TITLE
Rotatable markers?

### ISSUE THREAD

**Issue by 8Duke8** [ibrierley/flutter_map_dragmarker#13]

**Comment by 8Duke8** [comment]
Is there a way how to achieve rotatable draggable markers similarly like the original flutter_map markers that have rotate boolean property? I need draggable map markers to rotate on map rotation.

**Comment by ibrierley** [comment]
Do you mean you want them to anti-rotate to the map (so always upright), or rotate with the map (so the marker would not be upright)?

**Comment by 8Duke8** [comment]
I am sorry. Yeah, I need them always upright.

**Comment by ibrierley** [comment]
Ok, have added the option rotateMarker and bumper version to 1.1.0. Default is on, so it rotate opposite to the map rotation.

**Comment by ibrierley** [comment]
You're welcome, thanks for the feedback.

**Comment by 8Duke8** [comment]
@ibrierley one more question. Is there a way how to easily set the DraggableMarker to not be draggable at all? I can always use the original Marker, but a draggable boolean could come in handy :-). I would appreciate any tips. Thanks in advance.

**Comment by ibrierley** [comment]
There's no current easy way. One could probably swap out the gesturedetector in the code based on a toggle, but I'm not sure if there would be any odd unintended consequences doing it like that.

**Comment by 8Duke8** [comment]
@ibrierley thanks anyway
