### ISSUE TITLE
Flutter_Map v2.0.0 - Incompatible

### ISSUE THREAD

**Issue by hendrikdewilde** [ibrierley/flutter_map_dragmarker#15]
**pub get**

Running "flutter pub get" in .....                       
Because flutter_map_dragmarker 2.0.0 depends on flutter_map ^1.0.0 and no versions of flutter_map_dragmarker match >2.0.0 <3.0.0, flutter_map_dragmarker ^2.0.0 requires flutter_map ^1.0.0.
So, because ..... depends on both flutter_map ^2.0.0 and flutter_map_dragmarker ^2.0.0, version solving failed.
pub get failed (1; So, because ..... depends on both flutter_map ^2.0.0 and flutter_map_dragmarker ^2.0.0, version solving failed.)
**Process finished with exit code 1**

Flutter Doctor: 
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.795], locale en-ZA)
    • Flutter version 3.0.2 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
• No issues found!

**Comment by ibrierley** [comment]
Ok, try ^3.0.0 now.

**Comment by hendrikdewilde** [comment]
Thank you 
That was fast  :)

Working now
