### ISSUE TITLE
Flutter_Map no longer appears to have required parameters

### ISSUE THREAD

**Issue by benneca** [ibrierley/flutter_map_dragmarker#19]
the newest version of FLutter_Map (2.2.0) no longer has the following parameters on MapOptions :

- allowPanningOnScrollingParent
- plugins

with this being the case, how are we supposed to implement dragmarkers plugin with this version?

**Comment by ibrierley** [comment]
I think 2.2.0 should be fine, but not 3.0.0 ?

There's a beta version at https://pub.dev/packages/flutter_map_dragmarker/versions/4.0.0-beta.1 which may work (hasn't been tested with the latest flutter_map beta, but not sure much has changed there). I also need to add a bug fix at some point to dragmarker, but may not be until the weekend.

**Comment by benneca** [comment]
I was just about to comment that and close this, feel free to close, I accidentally pulled 3.0.0 when I meant to pull 2.2.0, Thanks
