### ISSUE TITLE
Flutter_Map v3.0.0 - Incompatible

### ISSUE THREAD

**Issue by hendrikdewilde** [ibrierley/flutter_map_dragmarker#20]
**pub get:**
Because flutter_map_dragmarker 3.1.0 depends on flutter_map ^2.0.0 and no versions of flutter_map_dragmarker match >3.1.0 <4.0.0, flutter_map_dragmarker ^3.1.0 requires flutter_map ^2.0.0.
So, because ......... depends on both flutter_map ^3.0.0 and flutter_map_dragmarker ^3.1.0, version solving failed.
pub get failed (1; So, because ......... depends on both flutter_map ^3.0.0 and flutter_map_dragmarker ^3.1.0, version solving failed.)
Process finished with exit code 1

**Flutter Doctor:**
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.856], locale en-ZA)
    • Flutter version 3.3.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (2 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0
• No issues found!

**Comment by ibrierley** [comment]
Try 4.0.0-beta.1 until I get chance to release a new one...

https://pub.dev/packages/flutter_map_dragmarker/versions/4.0.0-beta.1

**Comment by hendrikdewilde** [comment]
Thank you

**Comment by ibrierley** [comment]
I've released v4 proper now. It's no different to the beta, so likely no need to do anything.
