### ISSUE TITLE
Issue while dragging marker

### ISSUE THREAD

**Issue by RushikeshB97** [ibrierley/flutter_map_dragmarker#25]
Hello, 

Thank you for this much needed feature.

I have implemented this in mobile app, but when I try to drag marker, almost all the times it is the map which moves, is there anything I need to make, to make marker easily draggable?

Thanks in advance!

**Comment by ibrierley** [comment]
Have you tried updateMapNearEdge: false ? It's not clear if the marker is near the edge of the window or not.

**Comment by RushikeshB97** [comment]
Hello,

setting updateMapNearEdge: false, did not work for me.

I managed to solve this issue at most extent by adding ' absorbPanEventsOnScrollables: false ' in map options.

Also I added 'onTap' event in map and then programmatically moving marker to that position.

Feel free to close this thread.

Thanks!

**Comment by ibrierley** [comment]
Thanks for the feedback!
