### ISSUE TITLE
Draggable Markers don't register drag or tap events sometimes after zooming

### ISSUE THREAD

**Issue by SheenaJacob** [ibrierley/flutter_map_dragmarker#27]
**Platform :** macOS
**Dependencies :**
flutter_map: ^3.1.0
flutter_map_dragmarker: ^4.1.2
**Flutter Version :** Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
**Dart Version :** Dart 2.18.6 • DevTools 2.15.0

**Bug**

Sometimes when zooming in on a map the drag marker does not respond to drag or touch events. This does not occur every time, but only in certain instances.
Note : In the video below (@ 4 seconds), when trying to drag the marker the map is moved instead. Also the onTap callback is not triggered when this happens.

https://user-images.githubusercontent.com/60810797/231968543-1d3bcd5e-08cb-498f-830d-a65a47b6f334.mov

**Reproducing the Bug:**

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map/plugin_api.dart';
import 'package:flutter_map_dragmarker/dragmarker.dart';
import 'package:latlong2/latlong.dart';

void main() {
  runApp(const DragMarkerTest());
}

class DragMarkerTest extends StatelessWidget {
  const DragMarkerTest({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: FlutterMap(
            options: MapOptions(
              absorbPanEventsOnScrollables: false,
              center: LatLng(45.5231, -122.6765),
              zoom: 6.4,
            ),
            children: [
              TileLayer(
                  urlTemplate:
                      'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                  subdomains: const ['a', 'b', 'c']),
              DragMarkers(
                markers: [
                  DragMarker(
                    key: const ValueKey(1),
                    point: LatLng(45.2131, -122.6765),
                    width: 80.0,
                    height: 80.0,
                    offset: const Offset(0.0, -8.0),
                    builder: (ctx) => const Icon(Icons.location_on, size: 50),
                    onDragUpdate: (details, point) {
                      debugPrint("Dragged position: $point");
                    },
                    onTap: (point) {
                      debugPrint("Marker Tapped");
                    },
                    feedbackBuilder: (ctx) =>
                        const Icon(Icons.edit_location, size: 75),
                    feedbackOffset: const Offset(0.0, -18.0),
                    updateMapNearEdge: true,
                    nearEdgeRatio: 2.0,
                    nearEdgeSpeed: 1.0,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by ibrierley** [comment]
Thanks, it would good if you can get a handle on when that happens. I note "something" happens on the video at 3 secs in maybe ?
I note, that your drag after that doesn't align with the map drag (so map is moving slower than your cursor), which looks a little odd.

Is this only happening on macOS, have you tried it on mobile at all ?

**Comment by SheenaJacob** [comment]
Thanks. I've included a comment about when its happening. So bacsically none of the dragCallbacks or onTap events are called at some point, and its like the drag marker doesn't exist. I tried this on Windows as well, and faced the same problem, and I'll test it on Android and leave an update

**Comment by ibrierley** [comment]
I'd be interested to know if it still happens if you create the DragMarker separately (i.e in an initState our something, and just reference it in the build, so it's not recreated every build call)

**Comment by SheenaJacob** [comment]
I can try that out and let you know : )

**Comment by SheenaJacob** [comment]
https://user-images.githubusercontent.com/60810797/232028439-304f0c0e-79bb-40f1-854e-f2fa1ede167e.mov


Moving the marker in a case like this results only in the map being panned as shown below:

https://user-images.githubusercontent.com/60810797/232029544-d7f56971-98a0-4e96-8a21-245412f7b56a.mov

**Comment by ibrierley** [comment]
Out of interest, can you do another video...so drag the map about slowish, then do your zooming or whatever, and then when you get the problem, do a bit of general map dragging again.

Something else looks a bit strange in general that I mentioned earlier, as though your cursor isn't at the position it's appearing as, but the video is a bit too short to tell.

**Comment by SheenaJacob** [comment]
Uploading a longer video is a little difficult as there's a 10Mb size limit but I hope this is clearer :
https://user-images.githubusercontent.com/60810797/232040057-f9c83a44-b6cb-4a43-a9b2-8fa019473687.mp4

**Comment by SheenaJacob** [comment]
Thanks for your help : )

**Comment by ibrierley** [comment]
No problem, I know in Browsers, this type of thing happens often if we are using an html element inside another transformed element, so calculations can get confused.

As this happens in both Mac and Windows (I'm assuming this example is not in a browser on both Windows and Mac, if it is, then this may apply), I have no idea what may cause it, unless you are aware of some outer widgets doing something strange.

**Comment by SheenaJacob** [comment]
Ahh. Alright. Thanks. Well. I'm not using it in the browser right now, so I guess I'll just have to debug a little more.

**Comment by pablojimpas** [comment]
This issue seems to be resolved in the current `master` branch.
Please, @SheenaJacob confirm if you're unable to reproduce this bug now to close this issue, thanks!

**Comment by SheenaJacob** [comment]
@pablojimpas The issue doesn't seem to be related to flutter_map_dragmarker, as I've faced it with other widgets on flutter_maps so it can be closed. Thanks

**Comment by pablojimpas** [comment]
> @pablojimpas The issue doesn't seem to be related to flutter_map_dragmarker, as I've faced it with other widgets on flutter_maps so it can be closed. Thanks

Nice, feel free to test with the latest `flutter_map` release and the latest commit of this repo, I can't reproduce this problem with that setup.

**Comment by SheenaJacob** [comment]
Alright. I will. Thanks : )
