### ISSUE TITLE
how to include in a project?

### ISSUE THREAD

**Issue by barbalex** [ibrierley/flutter_map_dragmarker#3]
I couldn't find this plugin on https://pub.dev/packages.
Should I copy the files into my project?

**Comment by ibrierley** [comment]
You can link in your pubspec to the git repo...

eg
dependancy
  git:
    url: <giturl>
    ref: <Just if you need you can add a specific branch as an option>

I do intend to release at some point as well, but may be a wee while. Do shout if you need that though.

**Comment by ibrierley** [comment]
Sorry, the double space indentation was lost on those, but you should get the idea.

**Comment by barbalex** [comment]
Thanks, I forgot that
