### ISSUE TITLE
Not Compatible With latlong2 v0.9.0

### ISSUE THREAD

**Issue by ARASHz4** [ibrierley/flutter_map_dragmarker#31]
`Because flutter_map_dragmarker 4.1.3 depends on latlong2 ^0.8.0 and no versions of flutter_map_dragmarker match >4.1.3 <5.0.0, flutter_map_dragmarker ^4.1.3 requires latlong2 ^0.8.0.
So, because app depends on both latlong2 ^0.9.0 and flutter_map_dragmarker ^4.1.3, version solving failed.`

**Comment by ibrierley** [comment]
You should be able to use flutter_map 4.0 in the interim, and I think it will be ok, flutter_map 5.0 isn't officially released yet (assuming that's whats causing the issue) ?

**Comment by ARASHz4** [comment]
latlong2 v0.9.0 is not compatible it's not related to flutter_map 4.0!

> You should be able to use flutter_map 4.0 in the interim, and I think it will be ok, flutter_map 5.0 isn't officially released yet (assuming that's whats causing the issue) ?

**Comment by ibrierley** [comment]
What version of flutter_map are you using ?

**Comment by ARASHz4** [comment]
I use flutter_map v4.0.0 and flutter_map_dragmarker v4.1.3
and a can't use latlong2 v0.9.0 because flutter_map_dragmarker depends on latlong2 v0.8.0

**Comment by ibrierley** [comment]
ok, I see, I think there's a subtle difference with the pubspec versioning, I thought it was matched with flutter_map. Will try and get that updated when I get chance, or pull requests welcome!

**Comment by pablojimpas** [comment]
I've changed the version constraints to support both `0.8.0` and `0.9.0`, since there are no breaking changes for us. That will make this package compatible both with `flutter_map` v4 and with v5 when it comes out.

@ARASHz4 if you are using `flutter_map: ^4.0.0` from pub.dev you shouldn't be getting any errors.
