### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by barbalex** [ibrierley/flutter_map_dragmarker#4]
Once I know how to include this plugin into my project (https://github.com/ibrierley/flutter_map_dragmarker/issues/3) I will need it to be sound null safe.

As the project is not very big I could give it a go myself. But beware: I am a dart/flutter noob.

@ibrierley What do you think?

**Comment by ibrierley** [comment]
Let me take a quick look, as I think there's some other dependancies need updating now flutter_map has also, and I'll try and give some feedback how long it will be.

**Comment by barbalex** [comment]
latlong > latlong2

**Comment by ibrierley** [comment]
I'm probably going to run out of time today to upgrade to null safety, there's quite a bit to do, but I will do it in time, hopefully by the end of the weekend.

**Comment by barbalex** [comment]
Hopefully - but it's your project and you owe me nothing.

**Comment by ibrierley** [comment]
Hah, no, but I've been putting it off for a while, and I have another plugin which depends on this one.

**Comment by barbalex** [comment]
Oh, just found flutter_map_line_editor. Looks GREAT!

**Comment by ibrierley** [comment]
This is the bit that it depends on :D, so that will be done after.

**Comment by ibrierley** [comment]
Bit of a rush job, but I've created a branch nullsafety if you wanted to test it. 

(I haven't had time to do the dragmarket_widget_layer.dart, but the dragmarker.dart normal layer like in the example should work)

**Comment by barbalex** [comment]
I added this to my pubspec.yaml:
```yaml
flutter_map_dragmarker:
  git:
    url: https://github.com/ibrierley/flutter_map_dragmarker
    ref: nullsafety
```

and got:
```
Because latlong >=0.6.1 depends on logging >=0.11.3 <1.0.0 and latlong <0.6.1 requires SDK version >=1.8.0 <2.0.0, every version of latlong requires logging >=0.11.3 <1.0.0.


And because build_runner >=2.0.0 depends on logging ^1.0.0 and every version of flutter_map_dragmarker from git depends on latlong any, build_runner >=2.0.0 is incompatible with flutter_map_dragmarker from git.
So, because capturing depends on both flutter_map_dragmarker from git and build_runner ^2.0.2, version solving failed.

pub get failed (1; So, because capturing depends on both flutter_map_dragmarker from git and build_runner ^2.0.2, version solving failed.)
exit code 1
```

So latlong needs to be replaced with latlong2.

**Comment by ibrierley** [comment]
Think a pubspec didn't update, try now.

Ian

**Comment by barbalex** [comment]
Same result.

Seems that latlong still did not get updated: https://github.com/ibrierley/flutter_map_dragmarker/blob/nullsafety/pubspec.yaml#L30

**Comment by barbalex** [comment]
actually, slightly different result:
```
[capturing] flutter pub get
Running "flutter pub get" in capturing...                       
Because every version of flutter_map_dragmarker from git depends on latlong 0.8.0 which doesn't match any versions, flutter_map_dragmarker from git is forbidden.

So, because capturing depends on flutter_map_dragmarker from git, version solving failed.
pub get failed (1; So, because capturing depends on flutter_map_dragmarker from git, version solving failed.)
exit code 1
```

**Comment by barbalex** [comment]
Seems that you updated the version to 0.8.0 which is correct for latlong2.

Also, don't forget to update the imports: 
```dart
import 'package:latlong2/latlong.dart';
```

instead of:

```dart
import 'package:latlong/latlong.dart';
```

**Comment by barbalex** [comment]
Oh, you did update the imports: https://github.com/ibrierley/flutter_map_dragmarker/blob/nullsafety/lib/dragmarker.dart#L4

**Comment by ibrierley** [comment]
Yes, I think it's because I've got 2 slightly different versions I'm switching between...can you try again.

**Comment by barbalex** [comment]
Installs now. I'll try to implement it and see if I get it to work now.

**Comment by barbalex** [comment]
When launching the virtual device I get:
```
Launching lib\main.dart on sdk gphone x86 64 in debug mode...
lib\main.dart:1
../flutter/.pub-cache/git/flutter_map_dragmarker-e3747e9aa0594e2881ce2b3db197e1bdd9012bc9/lib/dragmarker.dart:65:67: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  DragMarkerWidget({this.mapState, required this.marker, AnchorPos? anchorPos, this.stream, this.options }); //: anchor = Anchor.forPos(anchorPos, marker.width, marker.height);                                                          
```
I am really just getting, but could this setting be meant? https://github.com/ibrierley/flutter_map_dragmarker/blob/nullsafety/pubspec.yaml#L17

**Comment by barbalex** [comment]
Yes: https://dart.dev/tools/pub/pubspec#sdk-constraints

**Comment by barbalex** [comment]
More to the point: https://dart.dev/guides/language/evolution

**Comment by ibrierley** [comment]
Ok, I've started with a fresh git version pulled from here, so hopefully it will track better. See if this does it.

**Comment by ibrierley** [comment]
Btw there should be a null safety branch for flutter_map_line_editor, couple of examples and demo gifs on readme if you wanted to try that as well. Thanks for patience.

**Comment by barbalex** [comment]
> Ok, I've started with a fresh git version pulled from here, so hopefully it will track better. See if this does it.

Works fine!

**Comment by barbalex** [comment]
> Btw there should be a null safety branch for flutter_map_line_editor, couple of examples and demo gifs on readme if you wanted to try that as well. Thanks for patience.

I'll leave that for the weekend.

**Comment by Mmisiek** [comment]
Can you upadate cupertino_icons to 1.0.3 or any on nullsafe branch ?

**Comment by ibrierley** [comment]
I'm just testing a new branch panfix as there was another issue with flutter_map 0.14 if you wanted to test that.

**Comment by Mmisiek** [comment]
Sure I can do that.

**Comment by pablojimpas** [comment]
This is not a problem any more. This package is compatible with full sound null safety, and therefore Dart 3 and Flutter 3.10. Closing…
