### ISSUE TITLE
CustomPoint unavailable in flutter stable version

### ISSUE THREAD

**Issue by Sabir-Islam-Khan** [ibrierley/flutter_map_dragmarker#7]
Hi,
I was trying to implement it on my app, but apparently i can't because Anchor and custompoint are missing. Is it because i am on stable ? Is there any way to use it on stable version  ? I really don't want to migrate now for a single feature as it's a very big project

**Comment by ibrierley** [comment]
Heya, I'm away until later in the week, but I think those are included with
flutter_map so make sure you have that included at the same level

**Comment by Sabir-Islam-Khan** [comment]
Found the problem. Your plugin is working till flutter_map: ^0.11.0 . Later CustomPoint got renamed to Point and several getters were removed as well. That's why it's not working on flutter_map latest version.

**Comment by ibrierley** [comment]
Thanks, youre welcome to submit a PR, or can sort when I'm back at weekend

**Comment by pablojimpas** [comment]
This issue is not relevant now.
